import { Address, DayOfWeekFlags, EntityType, FirstPaymentRule, PaymentMethodMode, PendingDeadlineAction, PendingForItem, Phone, SecondPaymentRule, SecurityDepositReleaseEmailType, SecurityDepositRule, SecurityDepositType, VisibleOptionRule } from "./CommonModels"

export interface Property{
  Key: string
  AddressId: number
  Name: string
  ExternalName: string
  DisplayOrder: number
  ExternalDisplayOrder: number
  InternalCode: string
  PublicUrl: string
  PhoneId: number
  NoAgreement: boolean
  FirstPaymentRule: FirstPaymentRule
  FirstPaymentAmount: number
  SecondPaymentRule: SecondPaymentRule
  SecondPaymentDays: number
  SecurityDepositRule: SecurityDepositRule
  SecurityDepositType: SecurityDepositType
  SecurityDepositAmount: number
  SecurityDepositDays: number
  SecurityDepositReleaseDays: number
  SecurityDepositReleaseEmailType: SecurityDepositReleaseEmailType
  SecurityDepositReleaseEmailTemplateId: number
  SecurityDepositReleaseRemindMe: boolean
  QuoteExpirationDays: number
  TravelInsuranceRule: VisibleOptionRule
  DamageProtectionProductId: number
  CalendarColor: string
  HasLinkedAvailabilityProperties: boolean
  Active: boolean
  MaxGuests: number
  MaxAdults: number
  MaxChildren: number
  MaxPets: number
  MinNights: number
  MaxNights: number
  MinHolidayNights: number
  MinWeekendNights: number
  MinGapNights: number
  MinGapNightsIsOverride: boolean
  RequireGapNights: number
  MinDisallowGapNights: number
  MaxDisallowGapNights: number
  ArrivalDays: DayOfWeekFlags
  DepartureDays: DayOfWeekFlags
  MinDaysBeforeArrival: number
  MaxDaysBeforeArrival: number
  RequireConfirmationForOnlineBookings: boolean
  PendingDaysForCreditCard: number
  PendingDaysForCheck: number
  PendingDaysForCustom: number
  DaysBeforeArrivalForCheck: number
  DaysBeforeArrivalForCustom: number
  PendingFor: PendingForItem
  PendingAction: PendingDeadlineAction
  PendingEmailTemplateId: number
  SendPaymentReminder: boolean
  SendSecurityDepositReminder: boolean
  CheckIn: string
  CheckOut: string
  TimeZoneId: string
  DisplayCulture: string
  ThemeOverrideId: number
  Latitude: number
  Longitude: number
  QuickBooksId: number
  QuickBooksClass: string
  QuickBooksDepartment: string
  QuickBooksCurrency: string
  QuickBooksRentItem: string
  CancellationPolicyId: number
  w_ThumbnailFileId: number
  AllowedPaymentMode: PaymentMethodMode
  RedirectAfterBookingUrl: string
  Address: Address
  Phone: Phone
  InquiryEmailAddress: string
  DisplayId: string
  EntityType: EntityType
  UserId: number
  DeletedUtc: Date
  DeletedUserId: number
  UpdatedUtc: Date
  UpdatedUserId: number
  CreatedUtc: Date
  CreatedUserId: number
  Id: number
}